### PR TITLE
Use /etc/pihole/versions file to gather version information

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

1) Instead of extracting the version information by hand from `pihole -v` we can use `/etc/pihole/versions` which contains all necessary information in a central place. 
2) Use the hash values to compare if versions are out of date.

**Note: this requires Pi-hole Core v5.14.1!**

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by DL6ER — CHANGES_REQUESTED** [review]
It doesn't seem to work and I unfortunately are currently lacking time myself right now to debug it. I'll try to check it out later.

Screenshot from 2022-11-19 08-22-43

while the file `/etc/pihole/versions` is readable by my user and contains:
```
CORE_BRANCH=master
WEB_BRANCH=doughnut
FTL_BRANCH=update/dnsmasq
CORE_VERSION=v5.14.1-0-g21026d9
WEB_VERSION=v5.17-2-gf841f309
FTL_VERSION=v5.19.2-4-g128096e7
GITHUB_CORE_VERSION=v5.14.1
GITHUB_WEB_VERSION=v5.17
GITHUB_FTL_VERSION=v5.19.2
```

**Comment by DL6ER** [comment]
Another comment looking at the screenshot above: Is `IPv6 Spt: Enabled` supposed to be red?

**Review by DL6ER — CHANGES_REQUESTED** [review]
Version will be something like
```
CORE_VERSION=v5.14.1
WEB_VERSION=v5.17-2-gf841f309
FTL_VERSION=v5.19.2-4-g128096e7
```
with a number of how many commits there have been after the last official release + the unique hash of the latest commit. The current script failed if there as anything else than a plain `v1.23(.45)` .

My suggestions change this by accepting anything that *starts* in a valid version string and isolates only this for the version comparison. There would have been too many changes to have Github suggestions working reasonably so I pushed my changes directly to your branch. Please have a look at the commit message detailing what was changed and review my code.

**Comment by yubiuser** [comment]
I don't think we should display a green version "tag" for everything that is different than `vUU.VV.WW`.

This is my current `versions` file
```
CORE_BRANCH=development
WEB_BRANCH=devel
FTL_BRANCH=development
CORE_VERSION=v5.14.2-7-g95e799ed
WEB_VERSION=v5.17-15-gec272dd1
FTL_VERSION=vDev-faf53fb
```
And with your modifications it looks like this:

Screenshot at 2022-12-02 17-34-07

I'm not using any `master` branch here, but it looks like I'm on exactly `v5.14.2` for `core` and `v5.17` for `web`. FTL will always fail as it returns `vDev` if not on `master` and will display `N/A`. So it is not consistent across the repos anyway. 

If users made any modifications to their repos we should not try to figure out on which version they are - because they are not on a released/tagged version but ahead
___

I like the idea of using the hash to compare if they are on the latest version, though.

**Comment by rdwebdesign** [comment]
You also could use alternative approaches:
- use yellow (or a different color) for these cases;
- replace the version with the string `mod` for modified branches;
- add an asterisk if you are on an alternative branch `v5.17*`, but this will increase the string length.

**Comment by DL6ER** [comment]
> but this will increase the string length.

What would happen right now if we have hotfixes everywhere? Without having tried it, I'm afraid
```
Pi-hole® vX.YY.Z, Web vX.YY.Z, FTL vX.YY.Z, PADD vX.YY.Z
```
could already be too long - even without any further annotations like `*`.

**Comment by yubiuser** [comment]
> `Pi-hole® vX.YY.Z, Web vX.YY.Z, FTL vX.YY.Z, PADD vX.YY.Z`

It fit's but it's tight.

(Slim does not have version information)
Screenshot at 2022-12-05 20-55-12
Screenshot at 2022-12-05 20-56-13
Screenshot at 2022-12-05 20-56-47

**Comment by yubiuser** [comment]
Rebased on latest `development`.

___

I  modified the code to check for the branch first. If it's not master, display version as `###` in yellow. (`mod` didn't look that well I think). If on master, compare hashes. If the are identical display version in green, otherwise in red.

**Comment by DL6ER** [comment]
I wonder ... why show the version as `###` if not on `master`? I am never on `master` actually (okay, I may not count), and what we had before (v5.4.3 in yellow if not on master) was at least providing *some* information

**Comment by yubiuser** [comment]
I  hesitate because I think it's kind of incorrect... custom branches have only a weak relation to released `tags`. One can have branches from branches from branches. To show "the last common ancestor tag" adds little value I think. The best would be to show the branch name (or part of it). Otherwise `mod`, `custom`,`branch,....

My biggest concern is that showing the "version" won't work in `FTL` as it does not show `v5.14.2-14-g32e693c5` but `vDev-faf53fb`. What do you want to display here? `vDev`? Then I would show `vDev` for all repos...

**Comment by rdwebdesign** [comment]
I understand your concern, but I have a different point of view.

As developers we use branches and branches from branches, but not everyone uses branches like this.

In most cases, users will be asked to use a branch as a temporary fix and they will be just waiting for the fix to be merged on the new release.
I think some additional info is better than removing the info. Replacing the version string entirely with `###`, or `---` (or `mod`, `custom`, `dev`, etc.) will show less info then a yellow version.

The branch name (or even the first N characters of the hash) could be a good idea.

About the FTL version: in my opinion if there is no option to show it, showing `###` or `vDev` will have the same effect.

**Comment by yubiuser** [comment]
This is how it looks with `branchname` truncated to the first 7 characters
Screenshot at 2022-12-09 22-21-56

**Comment by DL6ER** [comment]
Screenshot from 2022-12-10 11-28-53

Some comments on this (not all related to the PR at hand):

1. We should have a placeholder (suggestion `?` in case there is no branch available)
2. Why is there a `.` after `System is health.`? I see no `.` after anything else in the screenshot
3. Why is the TX and RX so close together when there is enough space available?

Concerning the "no branch is available": I don't know how this hapend but, indeed, all the variables `WEB_*=`are set to empty in my versions file. After running `pihole updatechecker`, everthing was fine:
Screenshot from 2022-12-10 11-36-17

This brings me to the next suggestion (sorry!): Replace the typical branch prefixes by abbreviations so we see more of the actual branch name (`fix/this` => `f/this`, `tweak/that` => `t/that`, `new/bie` => `n/bie`). It is especially bad with `tweak/...` as you can see above.

**Comment by yubiuser** [comment]
Screenshot at 2022-12-10 22-44-49

**Comment by rdwebdesign** [comment]
The versions are looking as expected here.

**Note:**
I'm using a test container to test this PR. This container wasn't used on the last 4 days, so there are no recent data.
That said, I'm seeing an unexpected (and very strange) output.
The "Router" information is completely wrong. The API responds with the correct value:

image

There's no `10.7.0.1` anywhere on my network (nor docker).

My other container running my production Pi-hole responds with the correct IP.

**Comment by yubiuser** [comment]
Check your `setupVars.conf` for `DHCP_ROUTER`

**Review by DL6ER — APPROVED** [review]
Screenshot from 2022-12-11 11-29-08

**Pull request merged**
