### PR TITLE
Revert IPv4 variable change made in commit 4203be5

### PR DESCRIPTION
**Pull request by christianboyle**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

This reverts a [prior change](https://github.com/pi-hole/PADD/commit/4203be51ca17868a0110650749db258af10547b5#diff-f0d2b00f20028b2c7f9febd84b9659afL675) that switched `${IPV4_ADDRESS}` to `${pi_ip_address}` which resulted in PADD displaying the `wlan0` address rather than `eth0` as it has historically.

The change was not made to other variants within [4203be5](https://github.com/pi-hole/PADD/commit/4203be51ca17868a0110650749db258af10547b5#diff-f0d2b00f20028b2c7f9febd84b9659afL675), so presumably it was a mistake.

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

`"IPv4:" "${pi_ip_address}"`
changes back to:
`"IPv4:" "${IPV4_ADDRESS}"`

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by DL6ER** [comment]
@fullburnen What do you think?

**Comment by dschaper** [comment]
Can you change the version string to `v3.4.1` please?

**Comment by christianboyle** [comment]
I went ahead and bumped the version on this again after rebasing.

**Comment by fullburnen** [comment]
Sorry, my email notifications all went to spam for some reason and I just saw the mention.

Yes, it was a mistake copied from elsewhere. Thanks for catching this!

**Pull request merged**
