### PR TITLE
Do not show update notices if `padd` is being run from the docker container

### LINKED ISSUE #324: "Updates are available" when using Pi-hole in Docker Container but "unable" to update PADD
**Describe the bug**
I'm running Pi-hole in a Docker Container with "latest" everything. But `PADD` could be updated, but it couldn't be updated until Docker Image will get this update. This might irritate or "frustate" users:
```
 __      __  __   
|__) /\ |  \|  \     Pi-hole® v5.14.2, Web v5.18, FTL v5.20, PADD v3.9.0
|   /--\|__/|__/     [✓] Core  [✓] FTL   [i] Updates are available
```

**Expected behavior**
I'm not exactly sure how `PADD` should inform Docker users that there is an update available for `PADD`… Maybe **let's discuss if this is not neccessary for Docker because Docker Images should always be considered as an All-in-One**!? 🤔  Or do you prefer an update-strategy **inside** a running Docker Container?

**Screenshots**
`docker exec -it pihole padd`
image

https://github.com/pi-hole/PADD/
image

https://github.com/pi-hole/docker-pi-hole/
image

### PR DESCRIPTION
**Pull request by PromoFaux**
### **What does this PR aim to accomplish?:**

Aims to resolve #324 by supressing the update available notice when PADD is run inside docker as this can cause confusion 

We can always tag a new version of the Pi-hole container to include the latest version of PADD, but it is not always possible to get to this straight away, so it is best to avoid showing users the update notice.

_(Thinking out loud: I wonder if it is worth building in logic that shows the container version/container update available instead of the rest of the component versions)_

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
- [x] I have read the above and my PR is ready for review. _Check this box to confirm_

### CODE REVIEW

**Comment by yubiuser** [comment]
> Thinking out loud: I wonder if it is worth building in logic that shows the container version/container update available instead of the rest of the component versions

I think this should be the way to go. Do you want to extend this PR?

**Comment by PromoFaux** [comment]
Sure, will take a look

**Review by rdwebdesign — DISMISSED** [review]

**Comment by yubiuser** [comment]
I think we should wait for @PromoFaux upcoming ideas...

**Comment by rdwebdesign** [comment]
No problem.
I thought the new ideas would be a new PR.

**Comment by PromoFaux** [comment]
paddd

**Review by yubiuser — COMMENTED** [review]
Did you check if `VersionConverter()` is working with the input from `DOCKER_VERSION` as expected?

https://github.com/pi-hole/PADD/blob/109ff806f3719c6c30ff34da5e4174b321db4972/padd.sh#L1052-L1054

I'm not sure what happens if we enter a 4 digit value in a 3 digit placeholder.

**Comment by PromoFaux** [comment]
No - I made an assumption here and just assumed it would work

Side note: I stumbled on `dpkg --compare-versions` yesterday ([see here for usage](https://github.com/pi-hole/pi-hole/pull/5133/files#diff-595630a29a855f6d667a84ca0662042e826bf3ec56322ef61d4a6ef149147d23R1439))... I wonder if it is worth exploring for this repository, and indeed in other places where we compare versions

**Comment by PromoFaux** [comment]
```console
admin@host:~$ echo "2022.01" | tr -d '[:alpha:]' | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }';
2022001000000
admin@host:~$ echo "2023.02.1" | tr -d '[:alpha:]' | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }';
2023002001000
```

**Comment by yubiuser** [comment]
Nice, thanks. It`s working because the first `%d` das no `03` before it.

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
