### PR TITLE
Fixes indentations and reverts a change to the IPv4 variable in PADDtiny

### PR DESCRIPTION
**Pull request by christianboyle**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

There were a few issues introduced in [PR 3.3.2](https://github.com/pi-hole/PADD/compare/v3.3.1...v3.3.2), specifically commit [4203be5](https://github.com/pi-hole/PADD/commit/4203be51ca17868a0110650749db258af10547b5).

I [created an issue](https://github.com/pi-hole/PADD/issues/127) describing the 3 problems. 

One of the problems was addressed (the header text alignment regression) and released as [v3.3.3](https://github.com/pi-hole/PADD/releases/tag/v3.3.3). 

There are 2 remaining bugs that were introduced in [3.3.2](https://github.com/pi-hole/PADD/commit/4203be51ca17868a0110650749db258af10547b5):

1. Indentation changes in section labels
2. Variable change for `IPv4` ([line 675](https://github.com/pi-hole/PADD/commit/4203be51ca17868a0110650749db258af10547b5#diff-f0d2b00f20028b2c7f9febd84b9659afR675))

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

zz

`3.3.1`: Pre-changes, things were stable here, but we should've had the section content indented one additional space (rather than removing the space on the section label as happened in the subsequent PR). The change should've happened this way to preserve the offset we had achieved in `3.3.1` (see the top center image in the screenshot showing the case overlapping the display on the left edge, obscuring some text).

`3.3.4`: Issues introduced:

- Section labels moved one space left
- IPv4 variable changed, resulting in a WiFi (.86) rather than Ethernet (.1) address being resolved

`this PR`: Issues fixed:

- Section labels moved right one space to restore offset
- Section content moved right two spaces to maintain design consistency (content indented one space relative to section label)
- IPv4 variable changed back to how it was in `3.3.1`: `${pi_ip_address}` -> `${IPV4_ADDRESS}`

At this point I think we have are using the maximum available space on this particular display with the `=` running to the right edge (no empty space after) and clearly readable labels on the left. 🥂

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by dschaper** [comment]
We seem to have alternating PRs. Can you collaborate with @fullburnen to come up with one PR that addresses all the Tiny issues? 

Thanks

**Comment by christianboyle** [comment]
@dschaper I believe that's what this PR does; I've retained the additional information that was added in @fullburnen's PR (IPv6, DNSSEC, etc.). The only additional changes I've made are to correct the indentation of section labels/content and to revert the IPv4 variable change (the IPv6 variable looks correct judging from the other PADD variants that display it).

**Comment by christianboyle** [comment]
I just noticed the ellipsis isn't staying on a single line and is wrapping now. I'll try to find a fix and update the PR asap.

**Comment by christianboyle** [comment]
Closing this as it doesn't seem possible to maintain single line truncation when indenting using this method. Will create a separate PR for the IPv4 variable fix.

**Pull request closed without merging**
