### PR TITLE
Issue 188: enable shellchecks SC2034 and SC2154

### PR DESCRIPTION
**Pull request by thomasmerz**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

---
**What does this PR aim to accomplish?:**
This PR enabled some trivial shellcheck warning that was disabled to make the code more correct.

**How does this PR accomplish the above?:**
SC2034 and SC2154 has been enabled, SC2059 has been disabled because I didn't find a good rewrite.
If you merge this after my other PR #189 then you can see the result from shellcheck in GitHub Action in this repository.

**What documentation changes (if any) are needed to support this PR?:**
There are no necessary changes to documentation.

### CODE REVIEW

**Comment by yubiuser** [comment]
I think PR in this repo should be made against `master` branch.

**Comment by thomasmerz** [comment]
@yubiuser
After PR #189 has been merged and after you have activated Stickler CI for this repo you should let Stickler check this out, too, before merging this PR. Thanks.

**Comment by yubiuser** [comment]
Why are there so many things commented out now?

**Comment by thomasmerz** [comment]
Sorry, I screwed up something - but I fixed it.
Output from "padd.sh" running in my Pi-hole docker container looks (still) good for me now:

grafik

**Comment by PromoFaux** [comment]
Is this PR meant for merging? There are a lot of unnessacery commits here, and still some commented out code? Might be best to start fresh...

**Pull request closed without merging**
