### PR TITLE
Use CHAOS TXT record to construct FTL's API URL

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Use `CHAOS` `TXT` record provided by FTL (https://github.com/pi-hole/FTL/pull/1793) to construct the API URL. This adds HTTPS support to PADD as well.

Uses the same logic implemented by https://github.com/pi-hole/pi-hole/pull/5499

Supersedes https://github.com/pi-hole/PADD/pull/375

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by DL6ER** [comment]
Seems to work as expected when running in the device itself. I tested without `--server` and then again with `localhost`, `ryzen` (my device's hostname) and `pi.hole`. Then again with a non-existing hostname (`--server local`) and got
```
                                              PADDmini  

                                              START UP =====================
dig: couldn't get address for 'local': not found
API not available. Please check connectivity
```
which does not look overly nice but does the job, I guess. Not sure if you want to improve on this or not.

---
Reading through the code, I was wondering if you want to include the explicit `--server localhost` case in
``` bash
if [ -z "${SERVER}" ]; then
```
as the other branch may fail here. It just didn't fail in my case because FTL is the local resolver of my Pi-hole (this isn't standard).

---

Now the test result from a different machine:
```

           __      __  __   
          |__) /\ |  \|  \  Pi-hole® Ad Detection Display
          |   /--\|__/|__/  A client for Pi-hole

          START UP ===================================================
curl: (6) Could not resolve host: ;;auth
curl: (6) Could not resolve host: communicationsauth
curl: (6) Could not resolve host: errorauth
curl: (6) Could not resolve host: toauth
curl: (7) Failed to connect to 127.0.0.1 port 80 after 0 ms: Connection refused
curl: (6) Could not resolve host: connectionauth
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: communicationsauth
curl: (6) Could not resolve host: errorauth
curl: (6) Could not resolve host: toauth
curl: (7) Failed to connect to 127.0.0.1 port 80 after 0 ms: Connection refused
curl: (6) Could not resolve host: connectionauth
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: communicationsauth
curl: (6) Could not resolve host: errorauth
curl: (6) Could not resolve host: toauth
curl: (7) Failed to connect to 127.0.0.1 port 80 after 0 ms: Connection refused
curl: (6) Could not resolve host: connectionauth
curl: (3) URL using bad/illegal format or missing URL
curl: (6) Could not resolve host: noauth
curl: (6) Could not resolve host: serversauth
curl: (6) Could not resolve host: couldauth
curl: (6) Could not resolve host: beauth
curl: (6) Could not resolve host: reachedauth
          Establishing connection with FTL...
curl: (6) Could not resolve host: reachedauth
          No response from FTL server. Please check connectivity and use the options to set the API URL
          Usage: padd.sh [--server <domain|IP>]
```

This does not look right. Running with `--server pi.hole` worked fine without any issues!

**Comment by yubiuser** [comment]
Thank for your review. I addressed both remarks. `localhost` is now considered, error handling is improved. I re-used the code from `core` where we perform the check for valid OS and get the list from our nameservers. Only detour is here that we're POSIX and can't use `$'..' to separate the lines.

**Comment by yubiuser** [comment]
Pinging @DL6ER

**Review by DL6ER — APPROVED** [review]
Working as expected, I just noticed one unrelated thing:

grafik

The API is sending this `null` because the information is not available on my embedded miniserver:
grafik

**Comment by yubiuser** [comment]
I added 2 commits: first only moves the output, second should address the "null" device.

**Review by DL6ER — APPROVED** [review]
grafik

**Pull request merged**
