### PR TITLE
Add "clients" to JSON output

### PR DESCRIPTION
**Pull request by pintomax**
Add "clients" to JSON output

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [ X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X ] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [ ] I am willing to help maintain this change if there are issues with it later.
- [X ] I give this submission freely and claim no ownership.
- [ X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ X] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
*A detailed description (such as a changelog) and screenshots (if necessary) of the implemented fix*

**What documentation changes (if any) are needed to support this PR?:**
*A detailed list of any necessary changes*

---
* You must follow the template instructions. Failure to do so will result in your pull request being closed.
* Please respect that Pi-hole is developed by volunteers, who can only reply in their spare time.

### CODE REVIEW

**Comment by thomasmerz** [comment]
@pintomax Sorry for asking, but I can't see any difference that your PR would introduce to user's experience 🤔 

image

**Comment by pintomax** [comment]
@thomasmerz the PR is meant for JSON output

./padd.sh --json
{"domains_being_blocked":97960,"dns_queries_today":23689,"ads_blocked_today":1285,"ads_percentage_today":5.424459,"clients": 21}

You can see that my PR is adding  the new property "clients" to JSON output

**Comment by pintomax** [comment]
@thomasmerz would you mind merging this PR if it's ok?

**Comment by thomasmerz** [comment]
@pintomax , sorry, I have no write access - I'm just a friendly user and sponsor of Pi-Hole 😁  We may ask @yubiuser , if he doesn't find this annoying… 🤷🏻‍♂️

**Comment by yubiuser** [comment]
Please increase the versions number as well.

**Comment by yubiuser** [comment]
That's not enough. Please bump again.
https://github.com/pi-hole/PADD/blob/1ce1d339a425a06d744009c40a4b7780784c8230/padd.sh#L20

**Review by yubiuser — APPROVED** [review]

**Comment by pintomax** [comment]
@DL6ER would you mind checking this PR and merge it to develop branch?

**Pull request merged**
