### PR TITLE
fix missing temperature display for certain non-pi hardware

### PR DESCRIPTION
**Pull request by Blumlaut**
**By submitting this pull request, I confirm the following:** 

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
CPU Temperature Readings were not working on (presumably) some non-pi devices, in my example (asus m5a97 evo r2 with FX8350 CPU), the temperature display only worked on Pi-hole -c, not padd, looking at the code, the Pi-hole chronometer already had included the code added in this PR to chronometer, see https://github.com/pi-hole/pi-hole/blob/41bdb741b7e1a70184ecd7dbfc23f3ebcaa5e3bc/advanced/Scripts/chronometer.sh#L204
This PR is basically just there to also include those two lines of code in Padd.

**How does this PR accomplish the above?:**
Temperature is now read from `/sys/class/hwmon/hwmon0/temp1_input`, if `/sys/class/thermal/thermal_zone0/temp` does not exist.

**What documentation changes (if any) are needed to support this PR?:**
N/A

### CODE REVIEW

**Comment by thomasmerz** [comment]
This looks good to me, https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface describes 
> To find all sensor chips, it is easier to follow the device symlinks from /sys/class/hwmon/hwmon*.

Could someone review and merge, please?

**Review by yubiuser — APPROVED** [review]
The PR is fine. However, `development` is out of date. Please rebase against current master and set the target branch to master. 
Please also increase the version number

**Comment by Blumlaut** [comment]
hope that does it.

**Comment by yubiuser** [comment]
Unfortunately not. Your PR now contains a two commits which are part of `development` and not `master`. It also changed permissions of `padd.sh`.

Maybe the easiest would be to start a new PR and cherry pick the right commit.

**Comment by Blumlaut** [comment]
> Unfortunately not. Your PR now contains a two commits which are part of `development` and not `master`. It also changed permissions of `padd.sh`.

yeah im not sure what weirdness git did there, i'll just re-fork and start over.

**Pull request closed without merging**
