### PR TITLE
Remove unused PADD.PID file

### PR DESCRIPTION
**Pull request by yubiuser**
- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [ ] I have commented my proposed changes within the code.
- [ ] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/contributing/).

---
**What does this PR aim to accomplish?:**
*A detailed description, screenshots (if necessary), as well as links to any relevant GitHub issues*

**How does this PR accomplish the above?:**
PADD used to write its current PID to `PADD.pid`. This was introduced in https://github.com/pi-hole/PADD/commit/ed23cdafbd2981dfaf407581dfd0038e61a4251d

However, the file seemed to be never used for anything.

### CODE REVIEW

**Comment by subnut** [comment]
> However, the file seemed to be never used for anything.

FWIW, we _could_ use it to prevent race conditions while modifying the `piHoleVersion` file when multiple `padd.sh` instances are running.

**Comment by yubiuser** [comment]
> I am not going to create a PR for it anytime soon.

Neither do I ;-)
Sure we could, but how many users run multiple `padd.sh`? We have not had a single complain about race conditions or failing `piHoleVersion` files so far.

**Comment by thomasmerz** [comment]
> We have not had a single complain about race conditions or failing `piHoleVersion` files so far.

I couldn't find any problem while running multiple instances of `/usr/bin/docker exec --tty pihole /etc/pihole/padd.sh` 🤷🏻‍♂️

**Comment by yubiuser** [comment]
The inital idea of adding a PID file is from https://github.com/pi-hole/PADD/pull/8. Following the link to the blog gives the reasons for adding it

> Why include the –pid option, you might ask? Good question! As I mentioned above, I wanted a way to be able to restart chronometer2 on my TFT display without having to reboot my Pi or doing any other tricky shenanigans. 

> So now whenever I want to tinker with the chronometer2 script in any way I just edit the script and/or my chronometer2.cmdline file, invoke the command ‘killc2‘, and after a short pause the script restarts on the TFT display with the new parameters and any other changes I made.

I'm not convinced if this enough reason to keep the file on **every user system**. There are other ways to kill the script.

**Comment by thomasmerz** [comment]
> I'm not convinced if this enough reason to keep the file on **every user system**. There are other ways to kill the script.

I would use `killall` or put `padd.sh` in a systemd-unit - not only for being able to easier restart it 😉 

```
🦎🖥  thomas@merz-nimbus:~ [0/5846]
10:57 $ systemctl status pihole-padd.service
● pihole-padd.service - PADD - A more advanced version of the chronometer provided with Pihole.
     Loaded: loaded (/etc/systemd/system/pihole-padd.service; enabled; vendor preset: disabled)
     Active: active (running) since Sun 2022-04-03 14:32:26 CEST; 20h ago
   Main PID: 10281 (sh)
      Tasks: 11 (limit: 4915)
     CGroup: /system.slice/pihole-padd.service
             ├─10281 /usr/bin/sh -c /usr/bin/docker exec --tty pihole /etc/pihole/padd.sh > /dev/tty11 < /dev/tty11
             └─10319 /usr/bin/docker exec --tty pihole /etc/pihole/padd.sh

Apr 03 14:32:26 merz-nimbus systemd[1]: Started PADD - A more advanced version of the chronometer provided with Pihole..
🦎🖥  thomas@merz-nimbus:~ [0/6060]
10:57 $ cat /etc/systemd/system/pihole-padd.service
# PADD - A more advanced version of the chronometer provided with Pihole.

[Unit]
Description=PADD - A more advanced version of the chronometer provided with Pihole.
#Requires=pihole.service
After=docker.service network-online.target dhcpd.service pihole.service

[Service]
Type=simple
Environment=TERM=linux
User=root
TTYPath=/dev/tty11
ExecStart=/usr/bin/sh -c "/usr/bin/docker exec --tty pihole /etc/pihole/padd.sh > /dev/tty11 < /dev/tty11"
ExecStop=/usr/bin/sh -c "/usr/bin/clear > /dev/tty11 < /dev/tty11"
Restart=always
RestartSec=1
TTYReset=yes
TTYVHangup=yes
TTYVTDisallocate=yes
KillSignal=SIGHUP

[Install]
WantedBy=multi-user.target
```

This can also be done without docker, just replace `ExecStart` and `ExecStop` and `After`.

**Comment by yubiuser** [comment]
Rebased on latest development

**Comment by yubiuser** [comment]
Rebased on latest development

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
