### PR TITLE
Consider REV_SERVER for Conditonal Forwarding; append domain to hostname only when DHCP is enabled.

### PR DESCRIPTION
**Pull request by Bucking-Horn**
**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [X] I have made only one major change in my proposed changes.
- [X] I have commented my proposed changes within the code.
- [X] I have tested my proposed changes, and have included unit tests where possible.
- [X] I am willing to help maintain this change if there are issues with it later.
- [X] I give this submission freely and claim no ownership.
- [X] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [ ] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).
---

Conditional Forwarding:
Pi-hole 5 introduced REV_SERVER for use in setupVars.conf for improved readability.
Currently, PADD only tests for the older CONDITIONAL_FORWARDING.
Probably CONDITIONAL_FORWARDING may be removed some time in the future.

For the time being, suggested implementation tests for both.

Hostname:
The current implementation expands hostname by domain as found in setupVars.conf if its not excessively long (e.g. to read raspberrypi.lan).
However, this is less likely to be true if Pi-hole is not configured as DHCP server, as the router's domain may differ.

Suggested implementation considers expansion only if Pi-hole is acting as DHCP server.

**What documentation changes (if any) are needed to support this PR?:**
None.

### CODE REVIEW

**Comment by dschaper** [comment]
Can you set line 20 to `v3.4` please?

**Comment by dschaper** [comment]
There's one other PR that needs to go first, #122, and then we'll probably need to update this PR on that new master. Once that is done then we can push this out as a new minor version.

**Comment by Bucking-Horn** [comment]
I've forced the change for padd_version.
How would I verify that change propagates here?

**Comment by dschaper** [comment]
Reload this page, it will show in the history as a force-push.

**Comment by dschaper** [comment]
Converting to draft so it doesn't accidentally get pushed before #122.

**Comment by dschaper** [comment]
Fixed simple merge conflict. The version variable was changed in this PR as well as in master so `git` blocked it.

**Pull request merged**
