### PR TITLE
update status of mega screen size

### PR DESCRIPTION
**Pull request by blurfl**
PADD reports "Pi-hole is offline" after temporarily disabling Pi-hole through the Web UI. This seems to only affect screens wider than 80 characters.

**By submitting this pull request, I confirm the following:** 
*please fill any appropriate checkboxes, e.g: [X]*

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md), as well as this entire template.
- [x] I have made only one major change in my proposed changes.
- [x] I have commented my proposed changes within the code.
- [x] I have tested my proposed changes, and have included unit tests where possible.
- [x] I am willing to help maintain this change if there are issues with it later.
- [x] I give this submission freely and claim no ownership.
- [x] It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
- [x] I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

Please make sure you [Sign Off](https://github.com/pi-hole/pi-hole/wiki/How-to-signoff-your-commits.) all commits. Pi-hole enforces the [DCO](https://github.com/pi-hole/pi-hole/wiki/Contributing-to-the-project).

---
**What does this PR aim to accomplish?:**
PADD reports "Pi-hole is offline" after temporarily disabling Pi-hole through the Web UI. This seems to only affect screens wider than 80 characters, the 'mega' screen size.

**How does this PR accomplish the above?:**
Adds a line to update the status of the mega screen size within the NormalPADD loop.

**What documentation changes (if any) are needed to support this PR?:**
None.

---

### CODE REVIEW

**Comment by dschaper** [comment]
Looks good, can you change the version string to `3.4.1` and we can send this out.

**Comment by dschaper** [comment]
If this is still applicable, please rebase your PR on the master branch and version this as 3.6.

Thank you.

**Comment by subnut** [comment]
Why hasn't this been merged? I just noticed that the status string never updates on my PADD display on mega size..

**Comment by yubiuser** [comment]
@blurfl 

Thanks for your PR and sorry for letting you waiting so long. I've been working on PADD a bit recently and saw your PR. I found a few more missing spots and fixed them in one of my commits which are part of the  larger PR https://github.com/pi-hole/PADD/pull/245. 
I added you as Co-author for this commit (https://github.com/pi-hole/PADD/pull/245/commits/a961b3c34f487bc7bdb4cfa173c0ac20c0f01d12)

**Pull request closed without merging**
