### PR TITLE
Modify tiny size to better match the look and layout of existing sizes

### PR DESCRIPTION
**Pull request by fullburnen**
I tried to match the existing layout as much as possible, including displaying the DHCP server info.

I don't have an IPv6 address, so that is blank in the screenshot.

dump

dump2

### CODE REVIEW

**Comment by dschaper** [comment]
Can you set line 20 to `v3.3.2` please?

**Comment by dschaper** [comment]
Also, this PR is in place of #121, or are both still valid?

**Comment by fullburnen** [comment]
There was a mistake and I accidentally included #121 in this branch. Would you prefer I keep them separate?

**Comment by dschaper** [comment]
No, it's fine. I wanted to know if it was okay to close #121 in favor of this PR.

**Comment by fullburnen** [comment]
Updated the version number.

In that case, it is fine to close #121.

**Comment by dschaper** [comment]
@fullburnen Send me an email dan.schaper@pi-hole.net and we'll get some swag out to you.

**Pull request merged**
